[package]
name = "c2"
version = "0.1.0"
authors = ["goofyblci"]
license = "MIT"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
rocket = "0.5.0"
rocket_ws = "0.1.0"
